# Generated by Django 2.2.7 on 2019-11-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.DataType')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.Region')),
            ],
        ),
    ]
