# Generated by Django 2.2.7 on 2019-11-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_datasource_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmaxmonthwise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tmaxmonthwise',
            name='udpated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
